# Generated by Django 2.2.3 on 2019-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190728_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], db_index=True, default='draft', max_length=16, verbose_name='status'),
        ),
    ]
