# Generated by Django 2.2.3 on 2019-07-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190729_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published', 'id'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft'), ('deleted', 'deleted')], db_index=True, default='draft', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=512, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('published', 'published'), ('draft', 'draft'), ('deleted', 'deleted')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('author', models.CharField(blank=True, max_length=512, null=True, verbose_name='author')),
                ('message', models.TextField(help_text='comment text', verbose_name='message')),
                ('like', models.PositiveIntegerField(blank=True, default=0, verbose_name='like')),
                ('dislike', models.PositiveIntegerField(blank=True, default=0, verbose_name='dislike')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='post')),
                ('reply', models.ForeignKey(blank=True, help_text='reply to comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Comment', verbose_name='reply')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('post', '-pk'),
            },
        ),
    ]
