# Generated by Django 2.2.3 on 2019-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190730_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish', '-id'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(max_length=64, unique=True, verbose_name='name'),
        ),
    ]
